Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-23.04-x86_64"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.cputopology :sockets => '1', :cores => '4', :threads => '1'
    libvirt.memory = 2048
  end
end
