- name: Git checkout
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ repo_dir }}"
    update: no

- include_role:
    name: "{{ playbook_dir }}/roles/fn/convert to HCL"

- name: packer init
  ansible.builtin.shell: packer init -upgrade template.json.pkr.hcl
  args:
    chdir: "{{ template_dir }}"
    creates: "/home/{{ ansible_env.USER }}/.config/packer/plugins/github.com/hashicorp/qemu"

