- name: set Headless false
  ansible.builtin.replace:
    path: "{{ template_dir }}/{{ headless_file }}"
    regexp: "default     = true"
    replace: "default     = false"
    after: 'variable "headless"'
    before: 'variable "http_directory"'
  when: not headless