- name: Git checkout
  ansible.builtin.git:
    repo: "https://gitlab.com/megabyte-labs/packer/ubuntu-desktop.git"
    dest: "{{ repo_dir }}"
    update: no

- include_role:
    name: "{{ playbook_dir }}/roles/fn/convert to HCL"

- name: packer init
  ansible.builtin.shell: packer init -upgrade template.json.pkr.hcl
  args:
    chdir: ToDo
    creates: "/home/{{ ansible_env.USER }}/.config/packer/plugins/github.com/hashicorp/qemu"

