- name: Git checkout Chef Bento
  ansible.builtin.git:
    repo: 'https://github.com/chef/bento.git'
    dest: "{{ bento_git_dir }}"
    # version: "{{ bento_version }}" # Breaks
    update: no

- name: packer init
  ansible.builtin.shell: packer init -upgrade ./packer_templates
  args:
    chdir: "{{ bento_git_dir }}"
    creates: "/home/{{ ansible_user }}/.config/packer/plugins/github.com/hashicorp/qemu"


- include_role:
    name: "{{role_path}}/patch: qemu builds"