# https://www.middlewareinventory.com/blog/ansible-dict/#How_to_Append_or_Add_items_into_Ansible_Dictionary
- name: vagrant box add from boxIndex
  ansible.builtin.shell: "vagrant box add {{item.name}} {{item.file}}"
  args:
    chdir: "{{build_dir}}/"
    creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/.vagrant.d/boxes/ubuntu-22.04"
  loop: "{{box_index}}"
