- name: Git checkout Chef Bento
  ansible.builtin.git:
    repo: "{{ git_url }}"
    dest: "{{ repo_dir }}"
    update: no

- name: packer init
  ansible.builtin.shell: packer init -upgrade ./packer_templates
  args:
    chdir: "{{ repo_dir }}"
    creates: "/home/{{ ansible_env.USER }}/.config/packer/plugins/github.com/hashicorp/qemu"


- include_role:
    name: "{{role_path | dirname}}/patch: qemu builds"