Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-Desktop-23.04-x86_64"

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 3
    libvirt.cputopology :sockets => '1', :cores => '3', :threads => '1'
    libvirt.memory = 4096

    libvirt.video_type = 'qxl'
  end
end
