- hosts: localhost #, fedora, ubuntu
  vars:
    # Host_vars
    ansible_become_password: u
    
  roles:
  - Bento
  - Petr Ruzicka
  # - broken/Megabyte Labs

- hosts: localhost
  vars:
    # Host_vars
    ansible_become_password: u    
  roles:
  - role: Petr Ruzicka/build
    tags: [ build, never ]
